name: MakoBlog Frontend Build Pipeline

env:
  CODE_ROOT: src
  FRONTEND_SLN: MakoBlogFrontend.sln
  FRONTEND_PROJ: src/Client/MakoBlogUI/

on:
  push:
    branches: [main]
    paths:
      - "${{ env.CODE_ROOT }}/Client/**"
      - "${{ env.CODE_ROOT }}/Common/**"
      - "${{ env.CODE_ROOT }}/${{ env.FRONTEND_SLN }}"
  pull_request:
    branches: [main]
    paths:
      - "${{ env.CODE_ROOT }}/Client/**"
      - "${{ env.CODE_ROOT }}/Common/**"
      - "${{ env.CODE_ROOT }}/${{ env.FRONTEND_SLN }}"
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore ${{ env.FRONTEND_SLN }}
        working-directory: ${{ env.CODE_ROOT }}/

      - name: Build
        run: dotnet build ${{ env.FRONTEND_SLN }} --no-restore --configuration Release
        working-directory: ${{ env.CODE_ROOT }}/

      - name: Upload Build Artefact
        uses: actions/upload-artifact@v2
        with:
          name: build-artefact
          path: |
            ${{ env.CODE_ROOT }}/Client/**/bin/
            ${{ env.CODE_ROOT }}/Client/**/obj/
            ${{ env.CODE_ROOT }}/Common/**/bin/
            ${{ env.CODE_ROOT }}/Common/**/obj/

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    if: ${{ success() && (github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch') }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore ${{ env.FRONTEND_SLN }}
        working-directory: ${{ env.CODE_ROOT }}/

      - name: Download Build Artefact
        uses: actions/download-artifact@v2
        with:
          name: build-artefact
          path: ${{ env.CODE_ROOT }}/

      - name: Unit Tests
        run: dotnet test ${{ env.FRONTEND_SLN }} --no-build --verbosity normal --configuration Release
        working-directory: ${{ env.CODE_ROOT }}/

  publish:
    name: Publish Frontend
    runs-on: ubuntu-latest
    needs: build
    if: ${{ success() && (github.event_name == 'push' || github.event_name == 'workflow_dispatch') }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore ${{ env.FRONTEND_SLN }}
        working-directory: ${{ env.CODE_ROOT }}/

      - name: Download Build Artefact
        uses: actions/download-artifact@v2
        with:
          name: build-artefact
          path: ${{ env.CODE_ROOT }}/

      - name: Publish Frontend
        run: dotnet publish --no-build --verbosity normal --configuration Release --runtime linux-x64 --self-contained true -p:BlazorEnableCompression=false
        working-directory: ${{ env.FRONTEND_PROJ }}/

      - name: Upload Frontend Published Artefact
        uses: actions/upload-artifact@v2
        with:
          name: frontend-published
          path: ${{ env.FRONTEND_PROJ }}/bin/Release/net6.0/publish/wwwroot
