name: SSH Deploy Frontend

on:
  workflow_run:
    workflows: ["MakoBlog Frontend Build Pipeline"]
    branches: [main]
    types:
      - completed

  workflow_dispatch:

jobs:
  deploy-test:
    name: "Deploy Frontend to Test"
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment:
      name: Test
      url: https://blog-dev.makodev.com.au
    env:
      DEPLOY_SOURCE: "${{ github.workspace }}/deploy"

    steps:
      - name: Download Published Client Artefact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: "frontend-build-pipeline.yml"
          workflow_conclusion: success
          name: frontend-published
          path: ${{ env.DEPLOY_SOURCE }}

      - run: ls ${{ env.DEPLOY_SOURCE }} -al

      - name: Clear destination directory
        uses: fifsky/ssh-action@v0.0.6
        with:
          command: "rm -rf ${{ secrets.DEPLOY_DIRECTORY }}/*"
          host: ${{ secrets.DEPLOY_HOST }}
          user: ${{ secrets.DEPLOY_USER }}
          port: ${{ secrets.DEPLOY_PORT }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: SCP Files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          source: ${{ env.DEPLOY_SOURCE }}/*
          target: ${{ secrets.DEPLOY_DIRECTORY }}
          strip_components: 3

  deploy-prod:
    name: "Deploy to Prod"
    runs-on: ubuntu-latest
    needs: deploy-test
    environment:
      name: Prod
      url: https://blog.makodev.com.au
    env:
      DEPLOY_SOURCE: "${{ github.workspace }}/deploy"

    steps:
      - name: Download Published Client Artefact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: "frontend-build-pipeline.yml"
          workflow_conclusion: success
          name: frontend-published
          path: ${{ env.DEPLOY_SOURCE }}

      - run: ls ${{ env.DEPLOY_SOURCE }} -al

      - name: Clear destination directory
        uses: fifsky/ssh-action@v0.0.6
        with:
          command: "rm -rf ${{ secrets.DEPLOY_DIRECTORY }}/*"
          host: ${{ secrets.DEPLOY_HOST }}
          user: ${{ secrets.DEPLOY_USER }}
          port: ${{ secrets.DEPLOY_PORT }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: SCP Files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          source: ${{ env.DEPLOY_SOURCE }}/*
          target: ${{ secrets.DEPLOY_DIRECTORY }}
          strip_components: 3
